const DEPARTMENTS = [
  'Accounting & Information Systems',
  'Anthropology',
  'Applied Chemistry & Chemical Engineering',
  'Arabic',
  'Archaeology',
  'Bangla',
  'Banking & Insurance',
  'Biochemistry & Molecular Biology',
  'Botany',
  'Chemistry',
  'Clinical Pharmacy & Pharmacology',
  'Clinical Psychology',
  'Communication Disorders',
  'Computer Science & Engineering',
  'Criminology',
  'Development Studies',
  'Disaster Science & Management',
  'Economics',
  'Educational & Counselling Psychology',
  'Electrical & Electronic Engineering',
  'English',
  'Finance',
  'Fisheries',
  'Genetic Engineering & Biotechnology',
  'Geography & Environment',
  'Geology',
  'History',
  'Information Science & Library Management',
  'Information Technology',
  'International Business',
  'International Relations',
  'Islamic History & Culture',
  'Islamic Studies',
  'Japanese Studies',
  'Journalism',
  'Law',
  'Linguistics',
  'Management',
  'Management Information Systems',
  'Marketing',
  'Mass Communication & Journalism',
  'Mathematics',
  'Microbiology',
  'Music',
  'Nuclear Engineering',
  'Nutrition & Food Science',
  'Organization Strategy & Leadership',
  'Pali & Buddhist Studies',
  'Peace & Conflict Studies',
  'Pharmaceutical Chemistry',
  'Pharmaceutical Technology',
  'Pharmacy',
  'Philosophy',
  'Physics',
  'Political Science',
  'Population Sciences',
  'Printing & Publication Studies',
  'Psychology',
  'Public Administration',
  'Robotics & Mechatronics Engineering',
  'Sanskrit & Hindu Studies',
  'Social Welfare',
  'Social Work',
  'Sociology',
  'Soil, Water & Environment',
  'Statistics',
  'Television, Film & Photography',
  'Theatre & Performance Studies',
  'Tourism & Hospitality Management',
  'Urdu',
  'Women & Gender Studies',
  'World Religions & Culture',
  'Zoology',
];

module.exports = DEPARTMENTS;
